Project init
WildCodeSchool/orleans-0219-php-aeromodelisme pull request #1
Opened 2019-04-11 15:38 UTC by jiceR

Initialisation du projet.

2019-04-11 15:39 UTC, Vincere1st commented
Control works, ok.

2019-04-11 15:42 UTC, open-it requested changes
tout à revoir, on se voit IRL

2019-04-11 16:29 UTC, jiceR commented
Correction done

2019-04-11 16:30 UTC, Vincere1st commented
Control correction, ok.

2019-04-12 07:36 UTC, open-it approved these changes

2019-04-12 07:36 UTC, merged