footer added to layout.html
WildCodeSchool/orleans-0219-php-aeromodelisme pull request #13
Opened 2019-04-17 15:16 UTC by jiceR

Mise en place du footer ds userlayout.html.

2019-04-18 05:53 UTC, sblondeau requested changes

2019-04-18 05:53 UTC, sblondeau commented on src/View/userlayout.html.twig
> +                <div class="info col-12 col-lg-2">
il existe une balise HTML address qui sert justement à mettre des adresses :p

2019-04-18 05:53 UTC, sblondeau commented on src/View/userlayout.html.twig
> +                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7563.623850719586!2d1.7710148156885803!3d47.91423451652312!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e4f
manque un retour à la ligne entre l'iframe et le form

2019-04-23 12:19 UTC, open-it approved these changes

2019-04-24 12:26 UTC, merged