Activities page
WildCodeSchool/orleans-0219-php-aeromodelisme pull request #19
Opened 2019-04-24 06:58 UTC by emilieserre

ajout de la page activités

2019-04-24 12:48 UTC, open-it requested changes
le nom de ta PR ne respecte pas la nomenclature demandée.

2019-04-24 12:48 UTC, open-it commented on src/Controller/ActivitesController.php
> +class ActivitesController extends AbstractController
Les noms tech doivent être en anglais donc Activities et non Activites

2019-04-24 12:48 UTC, open-it commented on public/assets/css/style.css
> +@include media-breakpoint-only(lg) {
je ne suis pas expert en css mais à priori il s'agit ici de mixin défini par bootstrap mais pour utiliser des mixins il faut un pré pocesseur scss (que vous n'avez pas sur les projets 2).

De plus, j'ai fais une recherche sur la classe car-columns et elle n'est pas présente dans ta page (/activites/index)

2019-04-24 12:48 UTC, open-it commented on src/View/base.html.twig
> +    <link rel="stylesheet" href="/assets/css/style.css">
Tes styles perso devraient être apres fontawesome. Sinon tu ne pourras pas utiliser (si besoin) fontawesome dans tes css perso.

2019-04-24 15:46 UTC, emilieserre commented on public/assets/css/style.css
> +@include media-breakpoint-only(lg) {
suppression de la partie du css qui est apparue miraculeusement et qui ne fait pas partie du css de cette pr

2019-04-24 15:46 UTC, emilieserre commented on src/Controller/ActivitesController.php
> +class ActivitesController extends AbstractController
modification des noms tech en anglais

2019-04-24 15:49 UTC, emilieserre commented on src/View/base.html.twig
> +    <link rel="stylesheet" href="/assets/css/style.css">
link style css positionné après la link fontawesome

2019-04-25 13:13 UTC, open-it requested changes
les modifs demandées ne sont pas présente.

2019-04-26 09:29 UTC, closed without merging