Sprint02 us12 partner
WildCodeSchool/orleans-0219-php-aeromodelisme pull request #24
Opened 2019-04-24 15:49 UTC by Nawalsubject

Ajout des partenaires dans le layout pour qu'il s'affiche sur chaque pages

2019-04-25 13:16 UTC, open-it requested changes

2019-04-25 13:16 UTC, open-it commented on src/View/userlayout.html.twig
> +{% include 'Home/partner.html.twig' %}
si c est une page inclus (et ca en est une) le fichier devrait se nommer _partner.html.twig. Si les partenaires sont affichés partout (ce que laisse comprendre cette PR), alors pourquoi ranger la vue partner dans le Home ?

2019-04-25 19:54 UTC, Nawalsubject commented on src/View/userlayout.html.twig
> +{% include 'Home/partner.html.twig' %}
En effet , j'ai modifié ! Je n'y avais pas pensé ..

2019-04-26 07:51 UTC, sblondeau requested changes
toutes les images de partner sont administrables, donc elles ne devraient pas etre versionnées.
ajouter les fichiers dans ce dossier dans le gitignore et faire un git rm --cached dessus pour les déversionnées.

2019-04-29 07:48 UTC, open-it approved these changes

2019-04-29 07:48 UTC, merged