add legal mentions page
WildCodeSchool/orleans-0219-php-aeromodelisme pull request #25
Opened 2019-04-25 10:16 UTC by Vincere1st

Add legal mention page

2019-04-25 13:17 UTC, open-it requested changes

2019-04-25 13:17 UTC, open-it commented on src/View/base.html.twig
> +    <link rel="stylesheet" href="/assets/css/style.css">
tes styles css perso devraient arrivés en dernier (pour pouvoir surcharger si nécessaire les styles bootstrap, fontawesome etc...)

2019-04-25 14:28 UTC, Vincere1st commented on src/View/base.html.twig
> +    <link rel="stylesheet" href="/assets/css/style.css">
Ce n'est pas mon css perso, c'était juste un changement de chemin (ajout du slash avant assets), car sinon le css n'était pas présent dans les autres pages. Merci.

2019-04-26 07:54 UTC, sblondeau requested changes

2019-04-26 07:54 UTC, sblondeau commented on src/Controller/LegalController.php
> +    public function mentionslegales()
en anglais les noms de methodes !

2019-04-26 07:54 UTC, sblondeau commented on src/Controller/LegalController.php
> +        return $this->twig->render('Legal/mentionslegales.html.twig');
et noms de fichiers twig egalement

2019-04-26 07:54 UTC, sblondeau commented on src/View/Legal/mentionslegales.html.twig
> +                        L'association est présidé par M. AUBRY Michel – 448 rue des écluses 45730 Mareau Aux Prés<br/>
présidée

2019-04-26 07:54 UTC, sblondeau commented on src/View/base.html.twig
> +    <link rel="stylesheet" href="/assets/css/style.css">
non ce que Nico voulais dire c'est que ce fichier style.css doit se trouver appeler APRES fontawesome (ligne d'en dessous) et non avant

2019-04-26 08:21 UTC, Vincere1st commented on src/View/base.html.twig
> +    <link rel="stylesheet" href="/assets/css/style.css">
Ok, fait. 
J'avais pas fait attention à ce détail, car c'était passé lors d'une autre PR, dsl.

2019-04-26 08:22 UTC, Vincere1st commented on src/Controller/LegalController.php
> +    public function mentionslegales()
ok, fait.

2019-04-26 08:23 UTC, Vincere1st commented on src/Controller/LegalController.php
> +        return $this->twig->render('Legal/mentionslegales.html.twig');
ok fait.
Comme le site est en français je pensais que l'url devait l'être aussi.

2019-04-26 08:23 UTC, Vincere1st commented on src/View/Legal/mentionslegales.html.twig
> +                        L'association est présidé par M. AUBRY Michel – 448 rue des écluses 45730 Mareau Aux Prés<br/>
ok.

2019-04-26 09:32 UTC, open-it approved these changes

2019-04-26 09:36 UTC, merged