Sprint02 us16 club informations
WildCodeSchool/orleans-0219-php-aeromodelisme pull request #28
Opened 2019-04-26 07:52 UTC by emilieserre

modif du style des titres + ajout de "/" dans le chemin du css

2019-04-26 08:01 UTC, sblondeau requested changes

2019-04-26 08:01 UTC, sblondeau commented on src/View/Informations/index.html.twig
> +                <h4 class="terrainTitle mb-4">Le terrain</h4>
la mise en page HTML ne va pas
Déjà tu n'as pas forcément besoin de mettre un `<p>` a chaque ligne. Parfois tu mets des tirets en début de phrase, dans ce cas c'est plutot un ul/li et non un p qui est pertinent ? 
et la classer terrainText peut être mis sur un conteneur parent et non sur chaque p.

2019-04-26 08:01 UTC, sblondeau commented on src/View/Informations/index.html.twig
> +            <h4 class="schemaTitle card-title">Schema du terrain</h4>
Schéma

2019-04-26 08:01 UTC, sblondeau commented on src/View/base.html.twig
> +    <link rel="stylesheet" href="/assets/css/style.css">
le style.css devrait etre appelé APRES le CSS de fontawesome

2019-04-26 08:01 UTC, sblondeau commented on src/View/Informations/index.html.twig
> +            <p>Nous vous accueillons sur un terrain de 4 hectars.</p>
hectares

2019-04-26 08:01 UTC, sblondeau commented on src/View/Informations/index.html.twig
> +            <p>Le club met à disposition de ses adhérents un club-house de 80m2.</p>
80m<sup>2</sup> pour mettre en exposant

2019-04-26 08:01 UTC, sblondeau commented on src/View/Informations/index.html.twig
> +            <p>L'association est équipé d'un bâtiment sur 2 étages dans lequel vous avez accès à des WC, lavabos, douches et à la WIFI</p>
et au WIFI
(WIFI est un nom masculin) https://www.larousse.fr/dictionnaires/francais/wi-fi/10910038)

2019-04-26 08:01 UTC, sblondeau commented on src/View/Informations/index.html.twig
> +            <p>L'association est équipé d'un bâtiment sur 2 étages dans lequel vous avez accès à des WC, lavabos, douches et à la WIFI</p>
équipée

2019-04-26 08:01 UTC, sblondeau commented on src/View/Informations/index.html.twig
> +                <p class="terrainText">- 1 piste en herbe de 180 x 60 m orientée Nord-Sud</p>
ici ul/li non ?

2019-04-26 08:46 UTC, emilieserre commented on src/View/Informations/index.html.twig
> +            <h4 class="schemaTitle card-title">Schema du terrain</h4>
j'ai mis tous les titres en majuscules pour plus de clarté(la police de caractère ne prend pas les accents et écrit d'office en majuscule)

2019-04-26 08:47 UTC, emilieserre commented on src/View/Informations/index.html.twig
> +                <h4 class="terrainTitle mb-4">Le terrain</h4>
j'ai conservé la mise en page avec des <p> sauf pour la partie avec les tirets(que j'ai retirés) pour faire une liste <ul><li>

2019-04-26 08:48 UTC, emilieserre commented on src/View/Informations/index.html.twig
> +                <h4 class="terrainTitle mb-4">Le terrain</h4>
oups !!! liste UL LI

2019-04-26 08:50 UTC, emilieserre commented on src/View/base.html.twig
> +    <link rel="stylesheet" href="/assets/css/style.css">
fait

2019-04-26 08:51 UTC, emilieserre commented on src/View/Informations/index.html.twig
> +            <p>Nous vous accueillons sur un terrain de 4 hectars.</p>
fait

2019-04-26 08:51 UTC, emilieserre commented on src/View/Informations/index.html.twig
> +            <p>Le club met à disposition de ses adhérents un club-house de 80m2.</p>
fait

2019-04-26 08:51 UTC, emilieserre commented on src/View/Informations/index.html.twig
> +            <p>L'association est équipé d'un bâtiment sur 2 étages dans lequel vous avez accès à des WC, lavabos, douches et à la WIFI</p>
fait

2019-04-26 08:51 UTC, emilieserre commented on src/View/Informations/index.html.twig
> +            <p>L'association est équipé d'un bâtiment sur 2 étages dans lequel vous avez accès à des WC, lavabos, douches et à la WIFI</p>
fait

2019-04-26 08:52 UTC, emilieserre commented on src/View/Informations/index.html.twig
> +                <p class="terrainText">- 1 piste en herbe de 180 x 60 m orientée Nord-Sud</p>
fait

2019-04-26 08:57 UTC, emilieserre commented
conflit résolu

2019-04-29 07:52 UTC, open-it approved these changes

2019-04-29 07:53 UTC, merged