S00 us03 header
WildCodeSchool/orleans-0219-php-aeromodelisme pull request #5
Opened 2019-04-16 08:13 UTC by emilieserre

up loader du composer, création du header avec le logo qui sera présent dans toutes les pages sauf celles de l'administrateur. modification du css pour les besoins du header

2019-04-16 08:45 UTC, sblondeau requested changes

2019-04-16 08:45 UTC, sblondeau commented on public/assets/css/style.css
> +@media (max-width: 767.98px) {
non !
pas de mediaqueries déjà et surtout pas à 767.98px :/ ça c'est du bricolage qui ne doit fonctionner qu'avec ton écran.

2019-04-16 08:45 UTC, sblondeau commented on src/View/userlayout.html.twig
> +        <div class="hero-wrap" style="background-image: url('assets/images/avion2flip.jpg');">
pas de style en inline, please

2019-04-16 11:41 UTC, emilieserre commented
suppresion des media queries et du style background dans le html, ajout du backround du header dans le style css, modification du html et du css pour la responsive

2019-04-16 12:41 UTC, ManuWiizzle commented on public/assets/css/style.css
> +@media (max-width: 767.98px) {
il te reste une media queries ligne 102 de ton style css. je te laisse modifier avant une nouvelle pull request

2019-04-16 15:18 UTC, emilieserre commented
suppresion du media queries

2019-04-16 15:52 UTC, sblondeau approved these changes

2019-04-17 06:44 UTC, emilieserre commented
résolution des conflits

2019-04-17 06:55 UTC, merged