Sprint01 us10 descrip activities
WildCodeSchool/orleans-0219-php-aeromodelisme pull request #68
Opened 2019-04-30 12:06 UTC by emilieserre

anim avion ok

2019-04-30 13:17 UTC, open-it requested changes

2019-04-30 13:17 UTC, open-it commented on public/assets/css/style.css
> +    /*background: #1b1d21;*/
pas de code commenté

2019-04-30 13:27 UTC, emilieserre commented
suppression du code commenté fait

2019-04-30 15:05 UTC, open-it requested changes

2019-04-30 15:05 UTC, open-it commented on public/assets/js/style.js
> +function drawPlane  (canvas) {
non dsl, ton fichier se nomme style.js et il contient une fonction qui se nomme drawPlane... Donc ton fichier semble mal nommé

2019-04-30 15:05 UTC, open-it commented on public/assets/js/style.js
> +drawPlane(document.getElementById("sineCanvas"));
tu pourrais stp dissocier la partie creation de la fonction et la partie appel de la fonction

2019-04-30 15:05 UTC, open-it commented on src/View/base.html.twig
> +<script type="text/javascript" src="/assets/js/style.js"></script>
le code JS de l'avion ne doit se charger QUE dans la page contact, c est pour cela que tuas un block javascript

2019-04-30 15:29 UTC, emilieserre commented on src/View/base.html.twig
> +<script type="text/javascript" src="/assets/js/style.js"></script>
fait

2019-04-30 15:29 UTC, emilieserre commented on public/assets/js/style.js
> +function drawPlane  (canvas) {
fait

2019-04-30 15:35 UTC, emilieserre commented on public/assets/js/style.js
> +drawPlane(document.getElementById("sineCanvas"));
fait

2019-04-30 16:44 UTC, open-it requested changes
dommage on y etait presque....

2019-04-30 16:44 UTC, open-it commented on public/assets/js/drawPlane.js
> +        // img.src = "http://i.imgur.com/LsYmdkL.png";
pas de code commenté (il y en a d autre dans le fichier)

2019-04-30 18:34 UTC, emilieserre commented on public/assets/js/drawPlane.js
> +        // img.src = "http://i.imgur.com/LsYmdkL.png";
fait

2019-04-30 19:00 UTC, emilieserre commented on public/assets/js/drawPlane.js
> +        // img.src = "http://i.imgur.com/LsYmdkL.png";
suppresion du code commenté dans le fichier css par la même occasion

2019-05-02 08:19 UTC, open-it approved these changes

2019-05-02 08:36 UTC, merged